name: 'stylehub_dbt'
version: '1.0.0'

profile: 'stylehub'

model-paths: ["models"]
target-path: "target"
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  stylehub:
    staging:
      +materialized: table

    marts:
      core:
        +materialized: table

      personas:
        +materialized: table

      product:
        +materialized: table 